### ISSUE TITLE
Support for UUIDs

### ISSUE THREAD

**Issue by justmobilize** [toastdriven/restless#56]
Currently UUIDs fail both in that they can't be serialized and can't be used as a pk

I fould this pull request: https://github.com/toastdriven/restless/pull/49/files
and notice that Django it self will support this in 1.8.4: https://docs.djangoproject.com/en/1.8/releases/1.8.4/

I've manually updated my urls to this:

```
    @classmethod
    def urls(cls, name_prefix=None):
        return patterns('',
                        url(r'^$', cls.as_list(), name=cls.build_url_name('list', name_prefix)),
                        url(r'^(?P<pk>[-\w]+)/$', cls.as_detail(), name=cls.build_url_name('detail', name_prefix)),
                        )
```

I'm not a regex wiz, so there might be a better one. Would love this to be build in.

**Comment by hoprocker** [comment]
More generally, the default regex for detail views is defined as `(?P<pk>\d+)` -- just digits -- and not as something more general (like any urlpath-valid, non-slash character). This isn't even something that you need to wait for Django 1.8.4 to see; Django currently allows defining custom User classes, and has allowed [non-integer primary keys since 1.8](https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#specifying-a-custom-user-model).

I can't whip this up right now, but this should be solvable with a simple PR changing just [this line](https://github.com/toastdriven/restless/blob/master/restless/dj.py#L89).

**Comment by suchanlee** [comment]
+1

**Comment by Jerome-github** [comment]
https://github.com/toastdriven/restless/pull/49 was integrated.

**Comment by seocam** [comment]
We already support UUID since version 2.0.1
